"""
Report generation module.

Builds the Markdown report from the list of activities with hidden PRs.
"""

import os
from dataclasses import dataclass
from datetime import datetime

from strava import Activity


@dataclass
class ReportData:
    """Holds all data needed to generate the report."""

    generated_at: datetime
    mode: str
    date_from: str | None
    date_to: str | None
    activity_types: list[str]
    scanned_count: int
    hidden_prs: list[Activity]
    is_partial: bool = False
    run_url: str | None = None


def generate_report(data: ReportData) -> str:
    """
    Generate the full Markdown report content as a string.
    """
    types_display = ", ".join(data.activity_types) if data.activity_types else "All"

    if data.date_from and data.date_to:
        date_range = f"{data.date_from} → {data.date_to}"
    else:
        date_range = "All time"

    lines = [
        "# Strava Visibility Report",
        "",
        f"Generated: {data.generated_at.isoformat(timespec='seconds')}",
        "",
    ]

    if data.is_partial:
        lines += [
            "> ⚠️ **Partial report** — the Strava API rate limit was reached before all activities"
            " could be fetched. The results below cover only the activities scanned so far.",
            "",
        ]

    lines += [
        f"- Mode: {data.mode}",
        f"- Date range: {date_range}",
        f"- Activity types filter: {types_display}",
        f"- Activities scanned: {data.scanned_count}",
        f"- Hidden PRs found: {len(data.hidden_prs)}",
        "",
        "---",
        "",
        "## Hidden PRs — Should be PUBLIC",
        "",
        "Activities that have a segment PR but are not visible to everyone.",
        "",
    ]

    if data.hidden_prs:
        lines += ["| Name | Date | Type | Link |", "|------|------|------|------|"]
        for a in data.hidden_prs:
            lines.append(
                f"| {_escape_md(a.name)} | {a.start_date} | {a.activity_type}"
                f" | {_activity_url(a.id)} |"
            )
    else:
        lines.append("_No hidden PRs found._")

    if data.run_url:
        footer = f"_Generated by [Strava Visibility Tracker]({data.run_url})_"
    else:
        footer = "_Generated locally by [Strava Visibility Tracker](https://github.com/aguillem/strava-visibility-tracker)_"

    lines += ["", "---", "", footer]

    return "\n".join(lines) + "\n"


def write_report(content: str, generated_at: datetime) -> str:
    """
    Write the report content to a Markdown file.

    The filename includes the run timestamp: strava-visibility-report-YYYYMMDD-HHmmss.md
    Returns the path of the generated file.
    """
    os.makedirs("reports", exist_ok=True)
    filename = f"reports/strava-visibility-report-{generated_at.strftime('%Y%m%d-%H%M%S')}.md"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)
    return filename


def print_summary(data: ReportData) -> None:
    """
    Print a short summary to stdout.
    """
    print(f"Activities scanned: {data.scanned_count}")
    print(f"Hidden PRs (should be public): {len(data.hidden_prs)}")


def _activity_url(activity_id: int) -> str:
    """
    Return the public Strava URL for a given activity ID.
    """
    return f"https://www.strava.com/activities/{activity_id}"


def _escape_md(text: str) -> str:
    """
    Escape characters that would break a Markdown table cell.
    """
    return text.replace("|", "\\|")
